repos:
    # Shellcheck - Static analysis
    -   repo: https://github.com/koalaman/shellcheck-precommit
        rev: v0.9.0 # Latest stable version
        hooks:
            -   id: shellcheck
                args: ["--severity=warning"]

    # shfmt - Shell Script Formatter
    -   repo: https://github.com/scop/pre-commit-shfmt
        rev: v3.12.0-2
        hooks:

            -   id: shfmt         # prebuilt upstream executable

    # bashate - Style Enforcement
    -   repo: https://github.com/openstack/bashate
        rev: 0.6.0 # Latest stable version
        hooks:
            -   id: bashate


