repos:
  # Shellcheck - Static analysis
  - repo: local
    hooks:
     - id: shellcheck
       name: shellcheck (system)
       entry: shellcheck
       language: system
       types: [shell]
       args: ["--external-sources", "--severity=warning"]
       files: \.(sh|bash|ksh|zsh)$

  # shfmt - Shell Script Formatter
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.12.0-2
    hooks:
    - id: shfmt         # prebuilt upstream executable
      args: ["-w", "-i", "4", "-ci"] # Customize formatting options

  # bashate - Style Enforcement
  - repo: https://github.com/openstack/bashate
    rev: 0.6.0 # Latest stable version
    hooks:
      - id: bashate


