# .github/workflows/lint.yml
name: shell-lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install linters
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt 

      - name: ShellCheck (static analysis)
        run: |
          set -euo pipefail
          mapfile -t shell_files < <(git ls-files '*.sh' '*.bash' '*.ksh' '*.zsh')
          if [ "${#shell_files[@]}" -eq 0 ]; then
            echo "No shell scripts detected — skipping ShellCheck."
            exit 0
          fi
          shellcheck --external-sources --severity=warning "${shell_files[@]}"

      - name: shfmt (format check, 4-space indent)
        run: |
           set -euo pipefail
          mapfile -t shell_files < <(git ls-files '*.sh' '*.bash' '*.ksh' '*.zsh')
          if [ "${#shell_files[@]}" -eq 0 ]; then
            echo "No shell scripts detected — skipping shfmt."
            exit 0
          fi
          shfmt -d -i 4 -ci "${shell_files[@]}"